/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVoiceRouteImport } from './routes/api/voice'
import { Route as ApiSbInspectRouteImport } from './routes/api/sb-inspect'
import { Route as ApiSbImageRouteImport } from './routes/api/sb-image'
import { Route as ApiSbAnalyzeRouteImport } from './routes/api/sb-analyze'
import { Route as ApiCowriterRouteImport } from './routes/api/cowriter'
import { Route as ApiConvertRouteImport } from './routes/api/convert'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceRoute = ApiVoiceRouteImport.update({
  id: '/api/voice',
  path: '/api/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSbInspectRoute = ApiSbInspectRouteImport.update({
  id: '/api/sb-inspect',
  path: '/api/sb-inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSbImageRoute = ApiSbImageRouteImport.update({
  id: '/api/sb-image',
  path: '/api/sb-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSbAnalyzeRoute = ApiSbAnalyzeRouteImport.update({
  id: '/api/sb-analyze',
  path: '/api/sb-analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCowriterRoute = ApiCowriterRouteImport.update({
  id: '/api/cowriter',
  path: '/api/cowriter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConvertRoute = ApiConvertRouteImport.update({
  id: '/api/convert',
  path: '/api/convert',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/cowriter': typeof ApiCowriterRoute
  '/api/sb-analyze': typeof ApiSbAnalyzeRoute
  '/api/sb-image': typeof ApiSbImageRoute
  '/api/sb-inspect': typeof ApiSbInspectRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/cowriter': typeof ApiCowriterRoute
  '/api/sb-analyze': typeof ApiSbAnalyzeRoute
  '/api/sb-image': typeof ApiSbImageRoute
  '/api/sb-inspect': typeof ApiSbInspectRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/cowriter': typeof ApiCowriterRoute
  '/api/sb-analyze': typeof ApiSbAnalyzeRoute
  '/api/sb-image': typeof ApiSbImageRoute
  '/api/sb-inspect': typeof ApiSbInspectRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/convert'
    | '/api/cowriter'
    | '/api/sb-analyze'
    | '/api/sb-image'
    | '/api/sb-inspect'
    | '/api/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/convert'
    | '/api/cowriter'
    | '/api/sb-analyze'
    | '/api/sb-image'
    | '/api/sb-inspect'
    | '/api/voice'
  id:
    | '__root__'
    | '/'
    | '/api/convert'
    | '/api/cowriter'
    | '/api/sb-analyze'
    | '/api/sb-image'
    | '/api/sb-inspect'
    | '/api/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiConvertRoute: typeof ApiConvertRoute
  ApiCowriterRoute: typeof ApiCowriterRoute
  ApiSbAnalyzeRoute: typeof ApiSbAnalyzeRoute
  ApiSbImageRoute: typeof ApiSbImageRoute
  ApiSbInspectRoute: typeof ApiSbInspectRoute
  ApiVoiceRoute: typeof ApiVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice': {
      id: '/api/voice'
      path: '/api/voice'
      fullPath: '/api/voice'
      preLoaderRoute: typeof ApiVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sb-inspect': {
      id: '/api/sb-inspect'
      path: '/api/sb-inspect'
      fullPath: '/api/sb-inspect'
      preLoaderRoute: typeof ApiSbInspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sb-image': {
      id: '/api/sb-image'
      path: '/api/sb-image'
      fullPath: '/api/sb-image'
      preLoaderRoute: typeof ApiSbImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sb-analyze': {
      id: '/api/sb-analyze'
      path: '/api/sb-analyze'
      fullPath: '/api/sb-analyze'
      preLoaderRoute: typeof ApiSbAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cowriter': {
      id: '/api/cowriter'
      path: '/api/cowriter'
      fullPath: '/api/cowriter'
      preLoaderRoute: typeof ApiCowriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/convert': {
      id: '/api/convert'
      path: '/api/convert'
      fullPath: '/api/convert'
      preLoaderRoute: typeof ApiConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiConvertRoute: ApiConvertRoute,
  ApiCowriterRoute: ApiCowriterRoute,
  ApiSbAnalyzeRoute: ApiSbAnalyzeRoute,
  ApiSbImageRoute: ApiSbImageRoute,
  ApiSbInspectRoute: ApiSbInspectRoute,
  ApiVoiceRoute: ApiVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
