/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVoiceRouteImport } from './routes/api/voice'
import { Route as ApiCowriterRouteImport } from './routes/api/cowriter'
import { Route as ApiConvertRouteImport } from './routes/api/convert'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceRoute = ApiVoiceRouteImport.update({
  id: '/api/voice',
  path: '/api/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCowriterRoute = ApiCowriterRouteImport.update({
  id: '/api/cowriter',
  path: '/api/cowriter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConvertRoute = ApiConvertRouteImport.update({
  id: '/api/convert',
  path: '/api/convert',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/cowriter': typeof ApiCowriterRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/cowriter': typeof ApiCowriterRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/cowriter': typeof ApiCowriterRoute
  '/api/voice': typeof ApiVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/convert' | '/api/cowriter' | '/api/voice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/convert' | '/api/cowriter' | '/api/voice'
  id: '__root__' | '/' | '/api/convert' | '/api/cowriter' | '/api/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiConvertRoute: typeof ApiConvertRoute
  ApiCowriterRoute: typeof ApiCowriterRoute
  ApiVoiceRoute: typeof ApiVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice': {
      id: '/api/voice'
      path: '/api/voice'
      fullPath: '/api/voice'
      preLoaderRoute: typeof ApiVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cowriter': {
      id: '/api/cowriter'
      path: '/api/cowriter'
      fullPath: '/api/cowriter'
      preLoaderRoute: typeof ApiCowriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/convert': {
      id: '/api/convert'
      path: '/api/convert'
      fullPath: '/api/convert'
      preLoaderRoute: typeof ApiConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiConvertRoute: ApiConvertRoute,
  ApiCowriterRoute: ApiCowriterRoute,
  ApiVoiceRoute: ApiVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
